name: chedy-v1
on:
  push:
    branches:
      - main
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: my first job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: npm ci
      - name: Test application
        uses: npm run test
