name: chedy-v1
on:
  push:
    branches:
      - main
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: my first job
    steps:
      name: Install dependencies
      run: npm ci

      name: Test application
      run: npm run test
